'use client';
import {useEffect,useState,useCallback} from 'react';
import AccessForm from './access-form';
import {Camera,Plus,ArrowUpRight,Link as LinkIcon,Pencil,Search,Check,FolderOpen,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
type Project={id:string;name:string;description:string;instructions:string;password_set:boolean};
type Album={id:string;project_id:string;section:string;number:string;title:string;teacher:string;url:string;complete:number;reviewer:string;updated:string;version:number};
type Data={admin:boolean;projects:Project[];albums:Album[]};
const defaults='Open a gallery and heart your favourite photos or leave comments in Lightroom. Return here when you have finished reviewing the whole album, enter your name, and mark Selection complete.';
export default function Hub({reviewId}:{reviewId?:string}){
 const [data,setData]=useState<Data|null>(null),[token]=useState(reviewId||''),[selected,setSelected]=useState(''),[section,setSection]=useState('All'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[name,setName]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[modal,setModal]=useState<'project'|'album'|'bulk'|null>(null),[draft,setDraft]=useState<any>({}),[formError,setFormError]=useState(''),[share,setShare]=useState('');

 const load=useCallback(async()=>{if(token===null)return;try{const r=await fetch('/api/hub'+(token?'?review='+encodeURIComponent(token):''));const d:any=await r.json();if(!r.ok){if(r.status===401||r.status===403)setData(null);throw Error(d.error);}setData(d);setSelected(old=>d.projects.some((p:Project)=>p.id===old)?old:d.projects[0]?.id||'');setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[token]);
 useEffect(()=>{load();const timer=setInterval(load,15000);const focus=()=>load();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[load]);
 const post=async(body:any)=>{const r=await fetch('/api/hub',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token})});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;};
 const project=data?.projects.find(p=>p.id===selected),albums=data?.albums.filter(a=>a.project_id===selected)||[],sections=Array.from(new Set(albums.map(a=>a.section))),complete=albums.filter(a=>a.complete).length,ready=albums.filter(a=>a.url&&!a.complete).length;
 const visible=albums.filter(a=>(section==='All'||a.section===section)&&(`${a.number} ${a.title} ${a.teacher}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='all'||(filter==='ready'&&a.url&&!a.complete)||(filter==='complete'&&a.complete)||(filter==='editing'&&!a.url)));
 const groups=(section==='All'?sections:[section]).filter(s=>visible.some(a=>a.section===s));
 async function save(e:React.FormEvent){e.preventDefault();setBusy('form');setFormError('');try{const result=await post({...draft,action:modal,project_id:selected});await load();if(modal==='project'&&!draft.id){setSelected(result.id);setSection('All');}setModal(null);setNotice('Changes saved.');}catch(e){setFormError((e as Error).message);}finally{setBusy('');}}
 async function toggle(a:Album,checked:boolean){if(!name.trim()){setError('Enter your name above the albums before marking a selection.');document.getElementById('reviewer')?.focus();return;}setBusy(a.id);setError('');try{await post({action:'complete',id:a.id,version:a.version,complete:checked,reviewer:name});await load();setNotice(checked?'Selection marked complete.':'Album reopened for review.');}catch(e){await load();setError((e as Error).message);}finally{setBusy('');}}
 function edit(kind:'project'|'album'|'bulk',item?:any){setFormError('');setDraft(item?{...item}:kind==='project'?{name:'',description:'',instructions:defaults}:kind==='album'?{title:'',number:'',section:section==='All'?'Act 1':section,teacher:'',url:''}:{lines:''});setModal(kind);}
 async function copyLink(){if(!project?.password_set)return;const link=location.origin+'/review/'+project.id;setShare(link);try{await navigator.clipboard.writeText(link);setNotice('Teacher review link copied.');}catch{setNotice('Copy the review link below.');}}
 function choose(id:string){setSelected(id);setSection('All');setSearch('');setFilter('all');setShare('');setNotice('');}
 return <div className="shell"><header className="topbar"><a className="brand" href="/"><img src="/logo.png" alt="Verbruggen Photography" className="brand-logo"/></a><div className="topnote">{data?.admin?'Your photography workspace':'Photo selections'}<span className="topbadge">{data?.admin?'Manager':'Reviewer'}</span>{data&&<Button variant="ghost" onClick={async()=>{try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout',project_id:token||undefined})});if(!r.ok)throw Error('Could not sign out. Please try again.');setData(null);setName('');setShare('');await load();}catch(e){setError((e as Error).message);}}}>{token?'Lock project':'Sign out'}</Button>}</div></header>
 <main><div className="page-heading"><div><p className="eyebrow">THE SELECTION ROOM</p><h1>{data?.admin?'Your projects. One place.':'Photo selections'}</h1></div>{data?.admin&&<Button className="primary" onClick={()=>edit('project')}><Plus size={17}/> New project</Button>}</div>
 {loading&&!data?<div className="empty"><LoaderCircle className="spin"/><h2>Opening your workspace…</h2></div>:!data?<><AccessForm reviewId={reviewId} onSuccess={load}/>{error&&!error.includes("Sign in")&&!error.includes("Enter the project")&&<p className="error">{error}</p>}</>:<>
 {data.admin&&<div className="project-grid">{data.projects.map((p,i)=>{const aa=data.albums.filter(a=>a.project_id===p.id),done=aa.filter(a=>a.complete).length;return <button key={p.id} className={'project-card '+(selected===p.id?'selected':'')} onClick={()=>choose(p.id)}><div className="project-meta"><span>PROJECT {String(i+1).padStart(2,'0')}</span>{selected===p.id?<span className="selected-label">Selected</span>:<ArrowUpRight size={18}/>}</div><h2>{p.name}</h2><p>{p.description||'Photo selections'}</p><div className="project-bottom"><span>{aa.length?`${done} / ${aa.length} complete`:'No albums yet'}</span><span>{aa.length?Math.round(done/aa.length*100)+'%':'—'}</span></div><Progress value={aa.length?done/aa.length*100:0} className="project-progress"/></button>;})}</div>}
 {project&&<section className="workspace"><div className="workspace-heading"><div><p className="eyebrow">{data.admin?'PROJECT OVERVIEW':'YOUR PROJECT'}</p><h2>{project.name}</h2>{!data.admin&&<p className="muted">{project.description}</p>}</div>{data.admin&&<div className="actions"><Button variant="outline" onClick={()=>edit('project',project)}><Pencil size={15}/> Project details</Button><Button variant="outline" disabled={!project.password_set} onClick={copyLink}><LinkIcon size={15}/> Share with teachers</Button></div>}</div>
 {data.admin&&!project.password_set&&<div className="share-box">Set a project password in <strong>Project details</strong> to enable teacher access.</div>}
 {share&&<div className="share-box"><label htmlFor="share">Teacher review link · share this link and the project password</label><Input id="share" readOnly value={share} onFocus={e=>e.target.select()}/></div>}
 <div className="instruction"><div><strong>Open a gallery. Choose your favourites. Mark it complete.</strong><p>{project.instructions||defaults}</p></div></div>
 <div className="stats"><div><strong>{albums.length}</strong><span>Total albums</span></div><div><strong>{ready}</strong><span>Ready to review</span></div><div><strong>{complete}</strong><span>Selections complete</span></div><div className="overall"><span>{albums.length?Math.round(complete/albums.length*100):0}% reviewed</span><Progress value={albums.length?complete/albums.length*100:0}/><small>{albums.filter(a=>!a.url).length} galleries still being edited</small></div></div>
 <div className="reviewer-row"><label htmlFor="reviewer">Your name <span>For the completion record</span></label><Input id="reviewer" placeholder="e.g. Leah" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><span className="sync-note">Changes save automatically · refreshes every 15 seconds</span></div>
 <div className="toolbar"><div className="search"><Search size={18}/><Input aria-label="Search albums or teacher" placeholder="Find an album or teacher…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="ready">Ready to review</option><option value="complete">Complete</option><option value="editing">Editing in progress</option></select>{data.admin&&<><Button variant="outline" onClick={()=>edit('bulk')}>Add in bulk</Button><Button onClick={()=>edit('album')}><Plus size={16}/> Add album</Button></>}</div>
 {!!sections.length&&<Tabs value={section} onValueChange={setSection}><TabsList className="act-tabs">{['All',...sections].map(s=><TabsTrigger key={s} value={s}>{s==='All'?'All albums':s}</TabsTrigger>)}</TabsList></Tabs>}
 <div aria-live="polite">{error&&<p role="alert" className="error">{error}</p>}{notice&&<p className="notice"><Check size={15}/>{notice}</p>}</div>
 {!visible.length?<div className="empty"><FolderOpen size={32}/><h3>{albums.length?'No matching albums':'Ready for a new story'}</h3><p>{albums.length?'Try another search or status.':data.admin?'Add the first album. You can paste its gallery link whenever the photos are ready.':'Galleries will appear here as they are added. Please check back soon.'}</p>{data.admin&&!albums.length&&<Button onClick={()=>edit('album')}><Plus size={16}/> Add first album</Button>}</div>:groups.map(group=><div className="album-group" key={group}><div className="group-heading"><h3>{group}</h3><span>{albums.filter(a=>a.section===group&&a.complete).length} of {albums.filter(a=>a.section===group).length} complete</span></div>{visible.filter(a=>a.section===group).map(a=><div className={'album-row '+(a.complete?'completed':'')} key={a.id}><span className="album-number">{a.number||'—'}</span><div className="album-title"><h4>{a.title}</h4><p>{a.teacher||'Photo gallery'}</p></div><div className="gallery-action">{a.url?<a href={a.url} target="_blank" rel="noreferrer" className="gallery-link">Open gallery <ArrowUpRight size={16}/></a>:<span className="editing">Editing in progress</span>}</div><div className="completion"><label><Checkbox aria-label={'Selection complete for '+a.title} checked={!!a.complete} disabled={!a.url||!!busy} onCheckedChange={v=>toggle(a,v===true)}/><span>{busy===a.id?'Saving…':'Selection complete'}</span></label>{a.updated&&<small>{a.complete?'Completed':'Reopened'} by {a.reviewer} · {new Date(a.updated).toLocaleDateString(undefined,{month:'short',day:'numeric'})} {new Date(a.updated).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</small>}</div>{data.admin&&<Button variant="ghost" size="icon" aria-label={'Edit '+a.title} onClick={()=>edit('album',a)}><Pencil size={16}/></Button>}</div>)}</div>)}
 </section>}</>}
 <footer><span>VERBRUGGEN PHOTOGRAPHY</span></footer></main>
 <Dialog open={!!modal} onOpenChange={open=>{if(!busy&&!open)setModal(null);}}><DialogContent className="edit-dialog"><DialogTitle>{modal==='project'?(draft.id?'Edit project':'New project'):modal==='bulk'?'Add albums in bulk':draft.id?'Edit album':'Add album'}</DialogTitle><DialogDescription>{modal==='project'?'Keep each shoot and its selections together.':modal==='bulk'?'One album per line. Leave the gallery link blank until it is ready.':'A gallery without a link appears as Editing in progress.'}</DialogDescription><form onSubmit={save} className="edit-form">{modal==='project'?<><label>Project name<Input required value={draft.name||''} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{draft.id?"New project password (leave blank to keep current)":"Project password"}<Input type="password" autoComplete="new-password" required={!draft.id||!draft.password_set} minLength={10} maxLength={128} value={draft.password||''} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><p className="muted">Use at least 10 characters. Share it separately from the review link. Changing it signs reviewers out; saved selections remain.</p><label>Description<Input value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Season, shoot or purpose"/></label><label>Instructions for teachers<Textarea rows={4} value={draft.instructions||''} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></label></>:modal==='bulk'?<label>Section | Number | Album name | Gallery link | Teacher<Textarea required rows={9} value={draft.lines||''} placeholder={'Act 1 | 1.1 | Album name | https://lightroom.adobe.com/… | Teacher\nAct 1 | 1.2 | Another album | | Teacher'} onChange={e=>setDraft({...draft,lines:e.target.value})}/></label>:<><div className="form-pair"><label>Act or section<Input required value={draft.section||''} onChange={e=>setDraft({...draft,section:e.target.value})}/></label><label>Program number<Input value={draft.number||''} placeholder="1.1" onChange={e=>setDraft({...draft,number:e.target.value})}/></label></div><label>Album name<Input required value={draft.title||''} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Teacher / choreographer<Input value={draft.teacher||''} onChange={e=>setDraft({...draft,teacher:e.target.value})}/></label><label>Gallery link<Input type="url" value={draft.url||''} placeholder="https://lightroom.adobe.com/shares/…" onChange={e=>setDraft({...draft,url:e.target.value})}/></label>{draft.id&&<p className="muted">Changing the gallery link reopens this album for review.</p>}</>}{formError&&<p className="error" role="alert">{formError}</p>}<Button disabled={!!busy} type="submit">{busy==='form'?'Saving…':'Save changes'}</Button></form></DialogContent></Dialog>
 </div>;
}
